source: excel
excel_file: db.xlsx

images_folder: images
no_name_user: ???

date_time_format: '%mD%dh%Hm%Ms%S'
log_file: log.txt

mode: facenet
test_mode: True
embedding_folder: facenet_embeddings

connection:
  host: 192.168.0.19
  login: api
  password: 1q2w3e4R

camera:
  id: 0
  frame_folder: frame
  frame_mode: full
  show: True
  reduce_frame: 2

face-recognition:
  num_jitters: 5
  tolerance: 0.51

facenet:
  threshold: 1.


turnstiles:
  area_1: [0.11, 0.0, 0.19, 1.0]  # x, y, w, h                    
  area_2: [0.34, 0.0, 0.2, 1.0]
  id_tur: 3
  min_time_diff: 7
